### ISSUE TITLE
大佬,我想用flutter实现小球物体互相碰撞的效果,不引入物理引擎能实现不?

### ISSUE THREAD

**Issue by o03150** [toly1994328/Flutter_Seven_Day#1]

**Comment by toly1994328** [comment]
可以啊，动态计算小球间的距离，当距离小于两球半径和，速度取反就行了

**Comment by o03150** [comment]
> 可以啊，动态计算小球间的距离，当距离小于两球半径和，速度取反就行了

如果再加上个重力呢

**Comment by toly1994328** [comment]
你可以看一下我的这篇文章:https://juejin.im/entry/5bee109b518825665f26e896

**Comment by o03150** [comment]
> 你可以看一下我的这篇文章:https://juejin.im/entry/5bee109b518825665f26e896

感谢,这篇文章写得很不错
